### ISSUE TITLE
json-server --watch db.json  in error

### ISSUE THREAD

**Issue by SirmaXX** [typicode/json-server#1014]
/usr/lib/node_modules/json-server/node_modules/depd/index.js:399
    throw new TypeError('argument fn must be a function')
    ^

TypeError: argument fn must be a function
    at Function.wrapfunction [as function] (/usr/lib/node_modules/json-server/node_modules/depd/index.js:399:11)
    at populateConstructorExports (/usr/lib/node_modules/json-server/node_modules/http-errors/index.js:264:45)
    at Object.<anonymous> (/usr/lib/node_modules/json-server/node_modules/http-errors/index.js:30:1)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/lib/node_modules/json-server/node_modules/send/index.js:15:19)

**Comment by SirmaXX** [comment]
thanks for anything ,it solved .everything working clearly
