### ISSUE TITLE
ERR_STRING_TOO_LONG

### ISSUE THREAD

**Issue by manonthemat** [typicode/json-server#1104]
I just discovered this library about a week ago and it has been very handy for mocking up some data. So thank you for that.

For a project of mine, I collected some real data and now run into the issue that I cannot use it with json-server. I am not ready to switch gears and write the actual API at this point, as I was hoping that the data would provide some further insights into the direction both the frontend and backend should develop.

The db.json I have compiled is about 1.5 gb in size. I'm running the json-server via `json-server --watch db/db.json -d 150 -H 0.0.0.0`.

This is the output:
```
  \{^_^}/ hi!

  Loading db/db.json
Error: Cannot create a string longer than 0x3fffffe7 characters
    at Object.slice (buffer.js:603:37)
    at Buffer.toString (buffer.js:800:14)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:58:23) {
  code: 'ERR_STRING_TOO_LONG'
}
```

It would be great if I could in fact use all the data, but I'd be okay with replacing the string in question with a custom value (preferably via command line argument).

**Comment by sparrowV** [comment]
Hi @manonthemat  I want to contribute. I'm just starting contributing to the open source projects and would be great if any one of you guys help me to get started
