### ISSUE TITLE
[bug] : full-text search not working

### ISSUE THREAD

**Issue by euskadi31** [typicode/json-server#136]
json-server v0.7.19
-------------------------

Hi,

I trying to make a search query.

~~~
https://api.acme.com/search?q=test
~~~

~~~json
{
    "search": [
        {
            "id": 1234,
            "name": "test 1",
            "status": true,
            "create_at": "2015-06-01T12:26:42+0000",
            "delete_at": null
        },
        {
            "id": 1235,
            "name": "test 2",
            "status": false,
            "create_at": "2015-06-01T15:35:12+0000",
            "delete_at": null
        }
    ]
}
~~~

~~~
TypeError: undefined is not a function
   at deepQuery (/usr/local/node/node-v0.12.0/lib/node_modules/json-server/src/mixins.js:61:11)
   at Function.deepQuery (/usr/local/node/node-v0.12.0/lib/node_modules/json-server/src/mixins.js:69:13)
   at /usr/local/node/node-v0.12.0/lib/node_modules/json-server/src/router.js:89:20
   at LazyWrapper.lazyValue [as value] (/usr/local/node/node-v0.12.0/lib/node_modules/json-server/node_modules/lodash/index.js:1141:28)
   at baseWrapperValue (/usr/local/node/node-v0.12.0/lib/node_modules/json-server/node_modules/lodash/index.js:2768:25)
   at LodashWrapper.wrapperValue (/usr/local/node/node-v0.12.0/lib/node_modules/json-server/node_modules/lodash/index.js:6104:14)
   at LodashWrapper._.value (/usr/local/node/node-v0.12.0/lib/node_modules/json-server/node_modules/lowdb/src/index.js:39:21)
   at LodashWrapper.<anonymous> (/usr/local/node/node-v0.12.0/lib/node_modules/json-server/node_modules/lowdb/src/index.js:18:35)
   at LodashWrapper.filter (/usr/local/node/node-v0.12.0/lib/node_modules/json-server/node_modules/lodash/index.js:3337:35)
   at list (/usr/local/node/node-v0.12.0/lib/node_modules/json-server/src/router.js:86:39)
~~~

**Comment by typicode** [comment]
Hi Axel,

Thanks for letting me know.
My bad, I've added a test for this case and it should be good now (`v0.7.20`).

**Comment by mehmetcan129** [comment]
![gitclone](https://cloud.githubusercontent.com/assets/12847657/9018197/3021f168-37e5-11e5-82aa-754cb9cbbbea.png)

I'm doing something but I saw this error. What does it mean ?
