### ISSUE TITLE
500 error for POST new profile and other errors

### ISSUE THREAD

**Issue by robert-dzikowski** [typicode/json-server#1387]
json-server version 0.17.1 running on Windows 10.

Inital db.json
```
{
    "posts": [
        { "id": 1, "title": "json-server", "author": "typicode" }
    ],
    "comments": [
        { "id": 1, "body": "some comment", "postId": 1 }
    ],
    "profiles": [{ "name": "typicode" }]
}

```

Bug 1. Sending POST /profiles with body { "name": "New Profile" } returns 500 error
```
TypeError: Cannot read properties of undefined (reading 'id')
    at Function.createId (C:\Users\Robert\AppData\Roaming\npm\node_modules\json-server\lib\server\mixins.js:58:39)
    at Function.insert (C:\Users\Robert\AppData\Roaming\npm\node_modules\json-server\node_modules\lodash-id\src\index.js:47:49)
    at C:\Users\Robert\AppData\Roaming\npm\node_modules\json-server\node_modules\lodash\lodash.js:4430:28
    at arrayReduce (C:\Users\Robert\AppData\Roaming\npm\node_modules\json-server\node_modules\lodash\lodash.js:697:21)
    at baseWrapperValue (C:\Users\Robert\AppData\Roaming\npm\node_modules\json-server\node_modules\lodash\lodash.js:4429:14)
    at LodashWrapper.wrapperValue (C:\Users\Robert\AppData\Roaming\npm\node_modules\json-server\node_modules\lodash\lodash.js:9114:14)
    at create (C:\Users\Robert\AppData\Roaming\npm\node_modules\json-server\lib\server\router\plural.js:239:48)
    at Layer.handle [as handle_request] (C:\Users\Robert\AppData\Roaming\npm\node_modules\json-server\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Robert\AppData\Roaming\npm\node_modules\json-server\node_modules\express\lib\router\route.js:144:13)
    at next (C:\Users\Robert\AppData\Roaming\npm\node_modules\json-server\node_modules\express\lib\router\route.js:140:7)
```

Bug 2. Posts aren't created.
POST /posts with body { "title": "Second Post", "author": "typicode" } creates post that includes only id, i.e. GET /posts/2 returns
```
{
        "id": 2
}
```

**Comment by robert-dzikowski** [comment]
It turned out that your server isn't compatible with Windows 10, because it works in WSL2, which is VM with Linux.
