### ISSUE TITLE
POST didn't update data

### ISSUE THREAD

**Issue by isnifer** [typicode/json-server#147]
Hi, guys!
On my pet project I have **http://localhost:3000/user** endpoint which returns:

``` json
"user": {
    "gold": 540,
    "coal": 12356,
    "coalSpeed": 20,
    "userpic": "",
    "mail": 3,
    "notifications": 13,
    "email": "john@doe.com",
    "username": "John",
    "notificationSettings": {
      "done": false,
      "box": true,
      "pm": false,
      "email": true
    }
 }
```

I tried to make **POST** _http://localhost:3000/user_ with data: 

``` json
{
    "gold": 540,
    "coal": 12356,
    "coalSpeed": 20,
    "userpic": "",
    "mail": 3,
    "notifications": 13,
    "email": "john@doe.com",
    "username": "CHANGE_THIS",
    "notificationSettings": {
      "done": false,
      "box": true,
      "pm": false,
      "email": true
    }
 }
```

And I getting an error:

``` js
TypeError: collection.push is not a function
    at Function.module.exports.insert (/usr/local/lib/node_modules/json-server/node_modules/underscore-db/src/index.js:59:18)
    at baseWrapperValue (/usr/local/lib/node_modules/json-server/node_modules/lodash/index.js:2778:30)
    at LodashWrapper.wrapperValue (/usr/local/lib/node_modules/json-server/node_modules/lodash/index.js:6104:14)
    at LodashWrapper._.value (/usr/local/lib/node_modules/json-server/node_modules/lowdb/src/index.js:39:21)
    at LodashWrapper.<anonymous> (/usr/local/lib/node_modules/json-server/node_modules/lowdb/src/index.js:18:35)
    at LodashWrapper.insert (/usr/local/lib/node_modules/json-server/node_modules/lodash/index.js:3337:35)
    at create (/usr/local/lib/node_modules/json-server/src/router.js:202:8)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/json-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/json-server/node_modules/express/lib/router/route.js:131:13)
    at next (/usr/local/lib/node_modules/json-server/node_modules/express/lib/router/route.js:125:14)
```

I found this method and understand that **collection** argument in my case is not an Array.
What I do wrong? I need to update collection.

**Comment by typicode** [comment]
Hi @isnifer,

Sorry for the delay, you need to use an array and a rewrite rule for singular resources.

`db.json`

```json
{
  "users": [{
    "id": 1,
    "gold": 540,
```

`routes.json`

```json
{
  "/user": "/users/1"
}
```

```
json-server db.json -r routes.json
```

**Comment by isnifer** [comment]
Ok, I tried your solution. It fix my problem, but it can't save changes.
my client code:
```js
fetch('http://localhost:3000/users/1', {
    method: 'POST',
    headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
    },
    body: JSON.stringify(payload)
}).then(data => {
    this.notifications.show({
        message: 'Изменения сохранены'
    });
});
```
My current state of first element in USERS array is:
```json
{
  "id": 1,
  "email": "lol@lol.com"
}
```
My payload:
```json
{
  "id": 1,
  "email": "john@doe.com"
}
```

**Comment by typicode** [comment]
If you change to a `PUT` it should work.

**Comment by isnifer** [comment]
@typicode I tried and this solution. But in this case ```json-server``` didn't update db.json.
Watch gif 
![json-server](https://cloud.githubusercontent.com/assets/1788245/8837378/bef75388-30ce-11e5-8dc1-525dda6d09c0.gif)

**Comment by typicode** [comment]
Thanks for the gif.
I thought it was good, tried with cURL but I must have missed something.

Anyway, in `v0.7.23` you can now have singular routes. No need to rely on rewrite rules.

For example, with the following `db.json`:

```json
{
  "user": {
    "name": "foo"
  },
  "posts": [
    { "id": 1, "body": "..." }
  ]
}
```

You can directly use `GET`, `POST`, `PUT` and `PATCH` on `http://localhost:3000/user`.
Since it's a new feature, let me know if you have issues with it.
