### ISSUE TITLE
error when checking Version (1.0.0-alpha.20)

### ISSUE THREAD

**Issue by Crypto69** [typicode/json-server#1484]
I get the following error when checking Version on the latest 1.0.0-alpha.20

`json-server --version     `
file:///usr/local/lib/node_modules/json-server/lib/bin.js:60
            const pkg = JSON.parse(readFileSync(join(__dirname, '../package.json'), 'utf8'));
                                                     ^

ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/usr/local/lib/node_modules/json-server/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at args (file:///usr/local/lib/node_modules/json-server/lib/bin.js:60:54)
    at file:///usr/local/lib/node_modules/json-server/lib/bin.js:91:49
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:120:12)

Node.js v21.5.0

**Comment by typicode** [comment]
Thanks for the report, I'll fix that 👍

**Comment by typicode** [comment]
Fixed
