### ISSUE TITLE
SyntaxError : Unexpected token '?' on Ubuntu 22.04

### ISSUE THREAD

**Issue by NonneTrapuE** [typicode/json-server#1495]
Hi.

I encounter an issue when i launch json-server in Ubuntu 22.04.
I install with NPM 
```
npm install -g json-server
``` 

And i have this error : 

file:///usr/local/lib/node_modules/json-server/lib/bin.js:32
                    default: process.env['PORT'] ?? '3000',
                                                  ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

Same error when i use npx. But, with same method, i installed and use json-server in Rocky Linux 9.

Have an idea ?

Thanks !

**Comment by NonneTrapuE** [comment]
Not good NodeJS version, my bad
