### ISSUE TITLE
Error on :  json-server --watch db.json

### ISSUE THREAD

**Issue by monupurohit** [typicode/json-server#1518]
json-server --watch db.json
C:\Users\purohit\AppData\Roaming\npm\node_modules\json-server\lib\bin.js:2
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by kaz1ngton** [comment]
Hi @monupurohit
As described in [`package.json`](https://github.com/typicode/json-server/blob/main/package.json#L14-L16), you should be using node version >=18.3. Check the current node version and update it if necessary :wink:

The `node:fs` module was released in node@16.*, and before that the `fs` module was used instead. My guess is that you just have the wrong version of node

**Comment by Makanda-h** [comment]
@kaz1ngton i have the same error but my node version won't update i have version 11.7.0
