### ISSUE TITLE
it doesn't work on xxx.js or remote url,though xxx.json is ok

### ISSUE THREAD

**Issue by nillwyc** [typicode/json-server#1543]
### my Node.js:v18.19.0

```JS
module.exports = () => {
  const data = { users: [] };
  // Create 1000 users
  for (let i = 0; i < 1000; i++) {
    data.users.push({ id: i, name: `user${i}` });
  }
  return data;
};
```

```shell
(base) PS T:\router> json-server --version
1.0.0-alpha.23

(base) PS T:\router> json-server http://jsonplaceholder.typicode.com/db
File http://jsonplaceholder.typicode.com/db not found

(base) PS T:\router> json-server --watch db.js
--watch/-w can be omitted, JSON Server 1+ watches for file changes by default
undefined:1
module.exports = () => {
^

SyntaxError: Unexpected token m in JSON at position 0
    at JSONFile.parse (<anonymous>)
    at JSONFile.read (file:///T:/myDev/env/nvm1.1.10/v18.19.0/node_modules/json-server/node_modules/lowdb/lib/adapters/node/DataFile.js:17:31)
    at async Observer.read (file:///T:/myDev/env/nvm1.1.10/v18.19.0/node_modules/json-server/lib/observer.js:21:22)
    at async Low.read (file:///T:/myDev/env/nvm1.1.10/v18.19.0/node_modules/json-server/node_modules/lowdb/lib/core/Low.js:16:22)
    at async file:///T:/myDev/env/nvm1.1.10/v18.19.0/node_modules/json-server/lib/bin.js:114:1

Node.js v18.19.0

**Comment by spanic** [comment]
Well, `.js` files are **not supported** anymore as a source for database generation, as it comes from

https://github.com/typicode/json-server/blob/6aa56d9581488d9bcd1baf42c4c97b293cd9ee99/src/bin.ts#L128-L136

Obviously, json-server expects only `.json5` and `.json` files, these changes have been made in PR https://github.com/typicode/json-server/pull/1468. However you can install latest `>= 0.X.X` version (`0.17.4` as for today), where `.js` still can be used:

https://github.com/typicode/json-server/blob/baf0aee90ae62a7afed180f49ce91b946f218f0e/src/cli/utils/load.js#L48-L62
