### ISSUE TITLE
Not able to source from https

### ISSUE THREAD

**Issue by tomdavidson** [typicode/json-server#233]
Hello, I am trying to source from a github gist rather than a local file:
```
jason-server -p 80 -w https://gist.githubusercontent.com/tomdavidson/9f2372e43712ff5a1cc1/raw/d7b03009e7bb40709a470f528628d45d5b11f574/json-sample.json

  \{^_^}/ hi!

  Loading https://gist.githubusercontent.com/tomdavidson/9f2372e43712ff5a1cc1/raw/d7b03009e7bb40709a470f528628d45d5b11f574/json-sample.json
  Done
evalmachine.<anonymous>:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'https:/gist.githubusercontent.com/tomdavidson/9f2372e43712ff5a1cc1/raw/d7b03009e7bb40709a470f528628d45d5b11f574/.~json-sample.json'
    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:584:18)
    at Object.fs.writeFileSync (evalmachine.<anonymous>:1224:33)
    at Object.module.exports.writeFileSync (/usr/local/lib/node_modules/json-server/node_modules/steno/index.js:76:6)
    at Object.module.exports.writeSync (/usr/local/lib/node_modules/json-server/node_modules/lowdb/src/disk.js:20:11)
    at Function.db.saveSync (/usr/local/lib/node_modules/json-server/node_modules/lowdb/src/index.js:109:10)
    at low (/usr/local/lib/node_modules/json-server/node_modules/lowdb/src/index.js:135:10)
    at Object.module.exports [as router] (/usr/local/lib/node_modules/json-server/src/server/router/index.js:28:10)
    at createApp (/usr/local/lib/node_modules/json-server/src/cli/run.js:39:27)
    at /usr/local/lib/node_modules/json-server/src/cli/run.js:111:13
```

**Comment by typicode** [comment]
Hi,

Thanks for raising this issue.
Data is loaded correctly but because it ends with `.json`, json-server thinks it's a file and fails to open it.

I'll fix that and release today.
