### ISSUE TITLE
Using json-server with BrowserSync

### ISSUE THREAD

**Issue by danielcrisp** [typicode/json-server#243]
Has anyone managed to get this working?

I'm using BrowserSync in my dev env to serve my web app and I'd like to use json-server to provide a fake JSON API accessible at `/api`.

I've tried to use json-server in the BrowserSync middleware option but that didn't work. Now I'm adding it in the BrowserSync callback but I always get the following error when I try to access an API route:

```
TypeError: Cannot read property 'data' of undefined
    at /lab/browsersync-json-server/node_modules/json-server/src/server/router/index.js:78:20
    at Layer.handle [as handle_request] (/lab/browsersync-json-server/node_modules/json-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/lab/browsersync-json-server/node_modules/json-server/node_modules/express/lib/router/index.js:312:13)
    at /lab/browsersync-json-server/node_modules/json-server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/lab/browsersync-json-server/node_modules/json-server/node_modules/express/lib/router/index.js:330:12)
    at next (/lab/browsersync-json-server/node_modules/json-server/node_modules/express/lib/router/index.js:271:10)
    at /lab/browsersync-json-server/node_modules/json-server/node_modules/express/lib/router/index.js:618:15
    at next (/lab/browsersync-json-server/node_modules/json-server/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/lab/browsersync-json-server/node_modules/json-server/node_modules/express/lib/router/index.js:176:3)
    at router (/lab/browsersync-json-server/node_modules/json-server/node_modules/express/lib/router/index.js:46:12)
```

It seems that `res.locals` is not defined. I understand BrowserSync uses Connect rather than Express.... could that be the problem?

I've created an isolated example here:

https://github.com/danielcrisp/browsersync-json-server 

Essentially it's just this:

**index.js**

```javascript
// require the module as normal
var bs = require('browser-sync').create();
var jsonServer = require('json-server');

// start the browserSync server
bs.init({
    server: {
        baseDir: './app'
    }
}, function (err, bs) {

    // access the browserSync connect instance
    bs.app.use(jsonServer.defaults());
    bs.app.use('/api', jsonServer.router('db.json'));

});
```

**db.json**

```json
{
  "posts": [
    {
      "id": 1,
      "title": "json-server",
      "author": "typicode"
    }
  ],
  "comments": [
    {
      "id": 1,
      "body": "some comment",
      "postId": 1
    }
  ],
  "profile": {
    "name": "typicode"
  }
}
```

What am I doing wrong?

**Comment by danielcrisp** [comment]
It seems the problem is indeed Connect. I've updated my repo with different examples, including using Connect and Express directly. Express works great.

So I guess the question is now **is it possible to make json-server work with Connect?**

**Comment by typicode** [comment]
I've tried this and it works with `/api/posts`:

```js
// access the browserSync connect instance
var server = jsonServer.create()
server.use(jsonServer.defaults())
server.use(jsonServer.router('db.json'))

bs.app.use('/api', server);
```

Another option can be to run json-server on another port `json-server --port 4000`. Since CORS is enabled, you can access `localhost:4000/posts` from `localhost:3000` in your front-end.

To start both in `package.json`, you can have:

```
"start": "npm run browserSync & npm run jsonServer & wait"
```

**Comment by danielcrisp** [comment]
Marvellous, thank you - the first option works nicely
