### ISSUE TITLE
happened an error 

### ISSUE THREAD

**Issue by drduan** [typicode/json-server#249]
```
[root@VM_30_164_centos /]#  json-server  --watch db.json

  \{^_^}/ hi!

  Loading db.json
  Done

  Resources

  Home
  http://localhost:3000

  Type s + enter at any time to create a snapshot of the database
  Watching...


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:929:3
[root@VM_30_164_centos /]#
```

**Comment by typicode** [comment]
It usually means that you have already a server listening on port 3000. 
You should check in your browser what is the server responding to `http://localhost:3000`.

If needed, you can make json-server listen on another port using `json-server --port 4000`.

**Comment by drduan** [comment]
And How to make server live while quit the command-client

**Comment by drduan** [comment]
<img width="495" alt="2016-03-17 17 53 07" src="https://cloud.githubusercontent.com/assets/7875572/13842447/26c11250-ec69-11e5-8d5a-402344c9fc9d.png">

**Comment by typicode** [comment]
`nohup` should do the trick (https://en.wikipedia.org/wiki/Nohup).
But there seem to be an issue with it  #221

**Comment by luan-analiseinfo** [comment]
kill -9 pidDoProcesso
