### ISSUE TITLE
Unexpected Identifier Syntax Error

### ISSUE THREAD

**Issue by WattsC-90** [typicode/json-server#260]
on windows, running the db.json file from the readme.md. Trying to run json-server and just get unexpected identifier errors.

I made sure that the file was utf-8 as that seemed to be feedback from someone else in a previous issue but that didnt sort it.

Any ideas what's going on here?

`> json-server --watch db.json
SyntaxError: Unexpected identifier
    at Object.exports.createScript (vm.js:24:10)
    at REPLServer.defaultEval (repl.js:235:25)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)`

db.json file: 
`{
  "posts": [
    { "id": 1, "title": "json-server", "author": "typicode" }
  ],
  "comments": [
    { "id": 1, "body": "some comment", "postId": 1 }
  ],
  "profile": { "name": "typicode" }
}`

**Comment by typicode** [comment]
Hi @WattsC-90,

It's a bit hard to see where it failed since there's no mention of any particular node module or json-server in the output.

Can you try `json-server http://jsonplaceholder.typicode.com/db`? Do you get an error?

**Comment by WattsC-90** [comment]
sorry to say, exactly the same error: 
`> json-server http://jsonplaceholder.typicode.com/db
SyntaxError: Unexpected identifier
    at Object.exports.createScript (vm.js:24:10)
    at REPLServer.defaultEval (repl.js:235:25)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)`

**Comment by typicode** [comment]
Oh, I think I see what's the issue.
I think you're running json-server this way:

```
C:\Users\...\> node
> json-server http://jsonplaceholder.typicode.com/db
```

Try running `json-server` directly without calling `node` REPL

```
C:\Users\...\> json-server --watch db.json
```

**Comment by WattsC-90** [comment]
I was indeed.. but now get:
`'json-server' is not recognized as an internal or external command,
operable program or batch file.`

i did run (with no errors):
`npm install -g json-server`

**Comment by WattsC-90** [comment]
ok, now that one seems to be a "me" problem, so let me track it down and get back to you..

**Comment by WattsC-90** [comment]
Ok, this was down to my system path being set correctly (embarassing)
make sure: `C:\Users\<|ProfileName|>\AppData\Roaming\npm` is in the System Variables path, not user variables path.

**Comment by typicode** [comment]
Congrats :)
