### ISSUE TITLE
Error responses

### ISSUE THREAD

**Issue by netsi1964** [typicode/json-server#352]
If I do say:

```
http://localhost:3000/posts?q=serve&q=comment
```

The case here has two `q` parameters, which confuses the search routine.
It should take only the first parameter or respond with a JSON based error (?).

I get an error text like this:

```
TypeError: q.toLowerCase is not a function at list (/usr/local/lib/node_modules/json-server/src/server/router/plural.js:89:13) at Layer.handle [as handle_request] (/usr/local/lib/node_modules/json-server/node_modules/express/lib/router/layer.js:95:5) at next (/usr/local/lib/node_modules/json-server/node_modules/express/lib/router/route.js:131:13) at Route.dispatch (/usr/local/lib/node_modules/json-server/node_modules/express/lib/router/route.js:112:3) at Layer.handle [as handle_request] (/usr/local/lib/node_modules/json-server/node_modules/express/lib/router/layer.js:95:5) at /usr/local/lib/node_modules/json-server/node_modules/express/lib/router/index.js:277:22 at Function.process_params (/usr/local/lib/node_modules/json-server/node_modules/express/lib/router/index.js:330:12) at next (/usr/local/lib/node_modules/json-server/node_modules/express/lib/router/index.js:271:10) at Function.handle (/usr/local/lib/node_modules/json-server/node_modules/express/lib/router/index.js:176:3) at router (/usr/local/lib/node_modules/json-server/node_modules/express/lib/router/index.js:46:12)
```

could be better if it had some JSON error :-)

**Comment by typicode** [comment]
I agree, good point :)
We should just take one query param and ignore others if there are duplicates.

**Comment by jacobwarduk** [comment]
I'd like to pick this up if it is available?

To clarify expected behaviour: 

**Given** the client is making a valid request to an endpoint.
**When** multiple `q` parameters are passed in the request.
**Then** only the first is evaluated and subsequent ones are ignored.

Is that correct?

**Comment by typicode** [comment]
Yes, thanks a lot for the PR 👍
