### ISSUE TITLE
Running error in events.js:141: Error: watch .dbus EACCES

### ISSUE THREAD

**Issue by chefarov** [typicode/json-server#392]
Installing on system ubuntu with kernel 4.4.0-45-generic and npm version 3.10.2

```
$ sudo npm install -g json-server
/usr/local/bin/json-server -> /usr/local/lib/node_modules/json-server/bin/index.js
/usr/local/lib
└── json-server@0.8.22 

npm WARN optional Skipping failed optional dependency /json-server/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```

Try to run giving a simple db.json file:
```
$ json-server --watch db.json

  \{^_^}/ hi!

  Loading db.json
  Done

  Resources
  http://localhost:3000/operators

  Home
  http://localhost:3000

  Type s + enter at any time to create a snapshot of the database
  Watching...

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch .dbus EACCES
    at exports._errnoException (util.js:870:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at createFsWatchInstance (/usr/local/lib/node_modules/json-server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/usr/local/lib/node_modules/json-server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/usr/local/lib/node_modules/json-server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/usr/local/lib/node_modules/json-server/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/usr/local/lib/node_modules/json-server/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/usr/local/lib/node_modules/json-server/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by typicode** [comment]
Hi @chefarov,

Could you retry with JSON Server `v0.9.0-beta`? The way `db.json` is watched has been improved.
To install it, use `npm install -g json-server@next`.

**Comment by chefarov** [comment]
Worked! Thank you typicode.

**Comment by typicode** [comment]
Great :)
