### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by gaxolio** [typicode/json-server#407]
Hi.
I am trying to update a db.json file.
This ia a section of my code:
```js
var jsonServer = require('json-server')
var jserver = jsonServer.create()
var router = jsonServer.router('db.json')
var middlewares = jsonServer.defaults()
var jsonServerPort = 3000;
jserver.use(middlewares)
jserver.use(router)
jserver.listen(jsonServerPort, function() {
    console.log('JSON Server is running on port:' + jsonServerPort);
})
```
a section of db.json

```json
"profiles": [{
            "firstName": "Sergio",
            "lastName": "Bertini",
            "type": "slave",
            "username": "sergio",
            "active": "Active",
            "id": 2,
            "userId": 2,
            "status": "Active"
        },
        {
            "firstName": "Simone",
            "lastName": "Braca",
            "type": "master",
            "username": "admin",
            "active": "Active",
            "id": 1,
            "selected": false,
            "userId": 1,
            "status": "Inactive"
        }
    ], 
```

http://localhost:3000/profiles works fine, return my profiles with no errors.

Then I want to PATCH a profile
POST http://localhost:3000/profiles/2
with boby
{"firstName":"Luigi"}

I get 
500 Internal Server Error

`ReferenceError: Promise is not defined
    at Object.write (/home/bertis/webgui/webserver/node_modules/json-server/node_modules/lowdb/lib/file-async.js:15:16)
    at LodashWrapper.db.write (/home/bertis/webgui/webserver/node_modules/json-server/node_modules/lowdb/lib/_index.js:57:26)
    at persist (/home/bertis/webgui/webserver/node_modules/json-server/node_modules/lowdb/lib/_index.js:70:12)
    at LodashWrapper.<anonymous> (/home/bertis/webgui/webserver/node_modules/json-server/node_modules/lowdb/lib/_index.js:78:5)
    at apply (/home/bertis/webgui/webserver/node_modules/json-server/node_modules/lodash/lodash.js:480:27)
    at LodashWrapper.wrapper [as value] (/home/bertis/webgui/webserver/node_modules/json-server/node_modules/lodash/lodash.js:5310:16)
    at update (/home/bertis/webgui/webserver/node_modules/json-server/src/server/router/plural.js:262:26)
    at Layer.handle [as handle_request] (/home/bertis/webgui/webserver/node_modules/json-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/bertis/webgui/webserver/node_modules/json-server/node_modules/express/lib/router/route.js:131:13)
    at next (/home/bertis/webgui/webserver/node_modules/json-server/node_modules/express/lib/router/route.js:125:14)`

but IN MEMORY db.json has been updated
```
{
    "firstName": "Luigi",
    "lastName": "Bertini",
    "type": "slave",
    "username": "sergio",
    "active": "Active",
    "id": 2,
    "userId": 2,
    "status": "Active"
}
```

Instead the real db.json is not changed.

Where is my error?
Thanks
Sergio

**Comment by typicode** [comment]
Hi @gaxolio,

What's your version of Node?

PS: I've edited your message to use ``` to format multilines :)

**Comment by gaxolio** [comment]
Hi. Thanks for your fast reply.
nodejs -v return v0.10.25

**Comment by typicode** [comment]
You're welcome. Actually, Promises aren't supported on `v0.10.25`. I would suggest updating to `v6.9.1` which is the current long term version or `v7`.

https://nodejs.org/en/

Personally, on Linux or OS X, I like to use [nvm](https://github.com/creationix/nvm) to install Node if that can help :)

**Comment by gaxolio** [comment]
@typicode , thanks!
I had some problem to update nodejs on my docker.
The docker in not managed by me. I asked for support to help me.
They updated to Ubuntu 16.04 and on the new Docker I have this nodejs version: v4.2.6.
It ss not the last stable nodejs version but I solved my problem.
Now I am able to update the db,json file without errors.
Great!
Thank you again.

**Comment by typicode** [comment]
You're welcome :) glad it works now :+1:
