### ISSUE TITLE
Cant start server after update

### ISSUE THREAD

**Issue by Savrov** [typicode/json-server#429]
Hello,
Today i've update to 0.9.2. After starting server i recieve message and cant get no data:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:3000
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:609:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
```
Any fix?

**Comment by veentoo** [comment]
Probably your server was already started
