### ISSUE TITLE
POST is creating Promise not defined error

### ISSUE THREAD

**Issue by spicecoder** [typicode/json-server#443]
when I use a post request , I am getting this error , although it creates the new record entry correctly :ReferenceError: Promise is not defined
    at Object.write (/usr/lib/node_modules/json-server/node_modules/lowdb/lib/file-async.js:13:16)
    at LodashWrapper.db.write (/usr/lib/node_modules/json-server/node_modules/lowdb/lib/_index.js:57:26)
    at persist (/usr/lib/node_modules/json-server/node_modules/lowdb/lib/_index.js:70:12)
    at LodashWrapper.
<anonymous> (/usr/lib/node_modules/json-server/node_modules/lowdb/lib/_index.js:78:5)
    at apply (/usr/lib/node_modules/json-server/node_modules/lodash/lodash.js:495:27)
    at LodashWrapper.wrapper [as value] (/usr/lib/node_modules/json-server/node_modules/lodash/lodash.js:5383:16)
    at create (/usr/lib/node_modules/json-server/lib/server/router/plural.js:230:50)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/json-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/json-server/node_modules/express/lib/router/route.js:131:13)
    at next (/usr/lib/node_modules/json-server/node_modules/express/lib/router/route.js:125:14)

Any idea what I am missing ?

**Comment by Nilegfx** [comment]
which node version do you use?
