### ISSUE TITLE
Cannot find module 'json-server'

### ISSUE THREAD

**Issue by amycheong19** [typicode/json-server#454]
I'm following the guide in README.md and I encountered error 
`Error: Cannot find module 'json-server'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/amycheong/Desktop/remote-json-server/dev/server.js:1:80)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)'`

when I `node server.js`

I have installed json-server globally.

**Comment by lamoglia** [comment]
Same here.

**Comment by Nilegfx** [comment]
Please post your implementation here (`server.js` content) if possible.

**Comment by lamoglia** [comment]
@Nilegfx , thanks for replying.
I'm using the same server.js shown on README.md:


```js
// server.js
var jsonServer = require('json-server')
var server = jsonServer.create()
var router = jsonServer.router('db.json')
var middlewares = jsonServer.defaults()

server.use(middlewares)
server.use(router)
server.listen(3000, function () {
  console.log('JSON Server is running')
})
```

```sh
$ node server.js
```

which results in

```
module.js:472
    throw err;
    ^

Error: Cannot find module 'json-server'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/fellipe/projetos/mdpontocom/fake-server/server.js:1:80)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by Nilegfx** [comment]
from the same directory you saved `server.js` file, could you please run
```sh which json-server```
and share with us the result

**Comment by Nilegfx** [comment]
anyway, I am assuming that you are missing a very very very simple and obvious step with I can't guess, so I'll write down the steps (sorry if it is super obvious for you) but just to make sure that we are in the same line.  

1. create a new directory (in your case I see you called it `fake-server`) 
2. copy the code snippet in `server.js` file
3. run `npm install json-server --g`
4. run `node server.js`

if you did the above and it is still not running, from the same directory that `server.js` file exist, run
`which json-server`and share the result of this command with us here.

**Comment by lamoglia** [comment]
Ok, thats probably some detail on my side...

1. create a new directory (done)
2. copy the code snippet (done)
3. run `npm install json-server --g` (seems ok, output below)
```
$ npm install json-server --g
/home/fellipe/.npm-global/bin/json-server -> /home/fellipe/.npm-global/lib/node_modules/json-server/bin/index.js
/home/fellipe/.npm-global/lib
└── json-server@0.9.5 
```

4. run `node server.js` (bad, output below)

```
$ node server.js 
module.js:472
    throw err;
    ^

Error: Cannot find module 'json-server'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/fellipe/fake-server/server.js:2:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

5. `$ which json-server`
```
$ which json-server
/home/fellipe/.npm-global/bin/json-server
```

6. `$ node --version` = `v7.5.0`
7. `$ npm --version` = `4.2.0`

**Comment by Nilegfx** [comment]
did you try `sudo node server.js`?

**Comment by lamoglia** [comment]
Yep :(

**Comment by Nilegfx** [comment]
mmm .. ok, try to install `json-server` locally (not globally) 

1. `npm init -y`
2. `npm install json-server`

-- 

You also could try: 
1. go to your server.js directory and run `npm link json-server`
2. run `node server.js`

-- 

aside from that, I highly recommend you to change your global node_modules directory by setting an Environment variable `NODE_PATH` to `/usr/lib/node_modules`

`export NODE_PATH=/usr/lib/node_modules`

**Comment by lamoglia** [comment]
Thanks a lot @Nilegfx, you solved it!

I've installed locally as you said (first 1.2.) and it worked. Then I've removed the local `node_modules/`and the `package.json`, reated the `NODE_PATH` env var, installed globally as I was doing earlier and it worked too.

**Comment by Nilegfx** [comment]
Glad to hear that, and BTW, the local installation didn't fix it, the `NODE_PATH` variable did.

**Comment by heejuny2** [comment]
> Thanks a lot @Nilegfx, you solved it!
> 
> I've installed locally as you said (first 1.2.) and it worked. Then I've removed the local `node_modules/`and the `package.json`, created the `NODE_PATH` env var, installed globally as I was doing earlier and it worked too.

Could you elaborate on this? I have the same issue. What do you mean by creating "NODE_PATH" env var?

**Comment by lamoglia** [comment]
> > Thanks a lot @Nilegfx, you solved it!
> > 
> > I've installed locally as you said (first 1.2.) and it worked. Then I've removed the local `node_modules/`and the `package.json`, created the `NODE_PATH` env var, installed globally as I was doing earlier and it worked too.
> 
> Could you elaborate on this? I have the same issue. What do you mean by creating "NODE_PATH" env var? 

If you're using Linux, this creates a NODE_PATH env var in your current terminal

`export NODE_PATH=/usr/lib/node_modules`

**Comment by redoc51624** [comment]
Why it is working in older version? but showing error in latest version

Error: Cannot find module 'json-server'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/fellipe/fake-server/server.js:2:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by sabard** [comment]
Also getting this error on `1.0.0-beta.3`, but not on `0.17.4`.

Tested on MacOS Sonoma 14.5, nvm versions `0.39.3` and `0.40.1`, and npm versions `20.15.0`, `20.18.0`, and `22.4.0`.

Followed all suggestions above with local/global installs, setting `NODE_PATH`, etc.

**Comment by amir-rafigh** [comment]
![Screenshot 2025-01-01 210401](https://github.com/user-attachments/assets/3b9f81ab-a302-43d8-a03e-e8a0fdcd2950)
Why doesn't the module code in the json-server exist at npm !!!!!!!!!!!!!

**Comment by teigorme** [comment]
Not install beta version, install this version json-server@^0.17.4
