### ISSUE TITLE
object is not a function

### ISSUE THREAD

**Issue by yabasha** [typicode/json-server#48]
I installed json-server globally and I followed the instruction to make a test json file:
`{
  "people": [
    {
      "fname": "Bashar",
      "lname": "Ayyash"
    }
  ]
}`

When I started json-server I received the following error:
C:\Program Files\nodejs\node_modules\json-server\bin\index.js:54
  server(object, filename).listen(port)
  ^
TypeError: object is not a function
    at start (C:\Program Files\nodejs\node_modules\json-server\bin\index.js:54:3)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\json-server\bin\index.js:68:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

Why is this?

Please advice,

**Comment by typicode** [comment]
Hi Ya,
It's a bug. I made a mistake in `v0.6.0`, fixed in `v0.6.1`.
Sorry for that.
