### ISSUE TITLE
JSON Server Not Loading with JSON File

### ISSUE THREAD

**Issue by ilovmylord** [typicode/json-server#529]
Hi All,

We have a JSON File which is around 700 MB.
We are trying to restart JSON Server with watching this file.
An error is thrown as below 

buffer.js:496
   throw new Error(‘“toString()” failed’);
   ^

Error: “toString()” failed
   at Buffer.toString (buffer.js:496:11)
   at Object.fs.readFileSync (fs.js:553:33)
   at Object.read (/usr/local/lib/node_modules/json-server/node_modules/lowdb/lib/file-sync.js:15:21)
   at LodashWrapper.db.read (/usr/local/lib/node_modules/json-server/node_modules/lowdb/lib/_index.js:36:29)
   at module.exports (/usr/local/lib/node_modules/json-server/node_modules/lowdb/lib/_index.js:96:15)
   at low (/usr/local/lib/node_modules/json-server/node_modules/lowdb/lib/index.node.js:12:10)
   at module.exports (/usr/local/lib/node_modules/json-server/lib/cli/utils/load.js:36:17)
   at start (/usr/local/lib/node_modules/json-server/lib/cli/run.js:119:5)
   at module.exports (/usr/local/lib/node_modules/json-server/lib/cli/run.js:156:3)
   at module.exports (/usr/local/lib/node_modules/json-server/lib/cli/index.js:76:3)

**Comment by ilovmylord** [comment]
Hey @typicode ,

We are stuck here . Please help

**Comment by typicode** [comment]
Hi,

Sorry for delay. 700MB is quite big for a JSON file and Node `fs.writeFileSync` seems to fail converting it to a string (maybe related https://github.com/nodejs/node/issues/9489)

I would try reducing the size of the file by removing all the data that you don't need to be mocked.
To quickly check if your file is small enough, you can run the following code and see if it works:

```js
const fs = require('fs')
const string = fs.readFileSync('db.json', 'utf-8')
JSON.parse(string)
```

You may want to try passing options to Node to increase some of the limits (not sure it would solve everything though)

**Comment by ziziermao** [comment]
May I ask if this is resolved? We are facing the same problem too.

**Comment by ziziermao** [comment]
We are using requests.js, one response is pretty large.

**Comment by ahmedabbas11** [comment]
any updates regrading this issue?
