### ISSUE TITLE
Require error (chalk.grey)

### ISSUE THREAD

**Issue by atropo** [typicode/json-server#59]
When I'm lauching the server-json I get this error:

```
TypeError: Object #<Chalk> has no method 'grey'
    at start (/home/giacomo/lib/node_modules/json-server/bin/index.js:41:23)
    at Object.<anonymous> (/home/giacomo/lib/node_modules/json-server/bin/index.js:83:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

I'm missing something?
Thanks

**Comment by typicode** [comment]
Hi @atropo,

Can't reproduce, could you try uninstalling and reinstalling.

```bash
$ json-server -v
0.6.6
$ json-server http://jsonplaceholder.typicode.com/db
{^_^} Hi!

Loading database from http://jsonplaceholder.typicode.com/db
  http://localhost:3000/posts
  http://localhost:3000/comments
  http://localhost:3000/albums
  http://localhost:3000/photos
  http://localhost:3000/users
  http://localhost:3000/todos

You can now go to http://localhost:3000/

Enter `s` at any time to create a snapshot of the db
```

I've updated code in `v0.6.7` to use chalk.gray instead of chalk.grey, just in case.

**Comment by atropo** [comment]
Hi @typicode, I've updated to v0.6.8 and now everything works fine.
Thanks!

**Comment by typicode** [comment]
Great :) you're welcome
