### ISSUE TITLE
Expand breaks on null values

### ISSUE THREAD

**Issue by Eiskis** [typicode/json-server#605]
With have the following db.json:

```json
{
"epics": [
  {
    "id": 1,
    "title": "My epic title"
  }
],
"tasks": [
  {
    "id": 1,
    "title": "Do one thing",
    "epicId": 1
  },
  {
    "id": 2,
    "title": "Do something else",
    "epicId": null
  }
]
}
```

The following request works: `tasks/1?_expand=epic`

The following request results in a 500: `tasks/2?_expand=epic`

This is the error message:

```
TypeError: Cannot read property 'toString' of null at /Users/myusername/Development/problemeer-api/node_modules/lodash-id/src/index.js:37:50 at baseFindIndex (/Users/myusername/Development/problemeer-api/node_modules/lodash/lodash.js:823:11) at findIndex (/Users/myusername/Development/problemeer-api/node_modules/lodash/lodash.js:7275:14) at Function.find (/Users/myusername/Development/problemeer-api/node_modules/lodash/lodash.js:5098:21) at Function.getById (/Users/myusername/Development/problemeer-api/node_modules/lodash-id/src/index.js:35:17) at /Users/myusername/Development/problemeer-api/node_modules/lodash/lodash.js:4379:28 at arrayReduce (/Users/myusername/Development/problemeer-api/node_modules/lodash/lodash.js:704:21) at baseWrapperValue (/Users/myusername/Development/problemeer-api/node_modules/lodash/lodash.js:4378:14) at LodashWrapper.wrapperValue (/Users/myusername/Development/problemeer-api/node_modules/lodash/lodash.js:9067:14) at /Users/myusername/Development/problemeer-api/node_modules/json-server/lib/server/router/plural.js:32:74
```

`null` values should be checked and returned as null when expanding.

**Comment by estaylorco** [comment]
What is the status of this fix?  This is a real problem.  I'm facing it now with a one-to-one relationship to a `jobTitles` table, where specifying the job title in a contact record is optional.

In order words, `jobTitleId: null` is possible.  Embed breaks in this case.

**Comment by ahmed-ghoniem** [comment]
As a workaround, you can change the null value to 0 
`
{
"epics": [
  {
    "id": 1,
    "title": "My epic title"
  }
],
"tasks": [
  {
    "id": 1,
    "title": "Do one thing",
    "epicId": 1
  },
  {
    "id": 2,
    "title": "Do something else",
    "epicId": 0
  }
]
}
`

**Comment by houcemlaw** [comment]
Will this fix be included in future releases?
I am stuck with undefined values: in my case the association id is not set unless requested. Entities are independent from each other. Relations are created when ever needed. 
We really appreciate it if you manage to handles both cases:
associationId = null or associationId = undefined

Thx!

**Comment by kendallroth** [comment]
This can be implemented via the following patch (applicable with `patch-package`), and allows specifying _optional_ expanded parents via a `?` suffix in the `_expand` key.

`GET /items?_expand=collection?`

```patch
diff --git a/node_modules/json-server/lib/server/router/plural.js b/node_modules/json-server/lib/server/router/plural.js
index 3e898ce..6b6ad4b 100644
--- a/node_modules/json-server/lib/server/router/plural.js
+++ b/node_modules/json-server/lib/server/router/plural.js
@@ -38,12 +38,19 @@ module.exports = (db, name, opts) => {
 
 
   function expand(resource, e) {
+    // PATCH: '_expand' params must be an array (not comma-separated string!)
     e && [].concat(e).forEach(innerResource => {
+      // PATCH: Optional expansions are indicated with '?' char
+      const isOptional= innerResource.endsWith("?");
+      innerResource = innerResource.replace("?", "");
+
       const plural = pluralize(innerResource);
 
       if (db.get(plural).value()) {
         const prop = `${innerResource}${opts.foreignKeySuffix}`;
-        resource[innerResource] = db.get(plural).getById(resource[prop]).value();
+        const idValue = resource[prop];
+        // PATCH: Allow 'expand' to reference optional parent fields (supports null/undefined parents)
+        resource[innerResource] = !isOptional || idValue ? db.get(plural).getById(idValue).value() : null;
       }
     });
   } // GET /name
```
