### ISSUE TITLE
Says Address in Use Even when it isn't 

### ISSUE THREAD

**Issue by Snazzyham** [typicode/json-server#630]
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1024:11)
```

So I keep getting this error, even when that specific port isn't in use. I know this because running json-server in terminal has it up and running, but using it as a module inside my node app does not. 

Here is the block of code I am using to run it 

```
function runServer() {
  const server = jsonServer.create();
  const router = jsonServer.router("./db.json");
  const middlewares = jsonServer.defaults();
  server.use(middlewares);
  server.use(router);
  server.listen(3000, () => {
    console.log("JSON Server is running");
  });
}
```

**Comment by luismasg** [comment]
thats classic.
just use the --port "something else"  ie:3001 
It means your console had a hiccup and left a running process in the background.
instead of terminating it. it just disconnected from the process.
you can use ps to find the PIDs and then kill them using the process id.

**Comment by Snazzyham** [comment]
Thanks for your response, after some testing, I noticed I was getting the error, but then if I went to localhost:3000, it would work anyway. Still doing some testing and trying to figure some stuff out, will report back if I find anything.

**Comment by Snazzyham** [comment]
Unrelated question, is there anyway to enable "watch mode" when not using it as a cli tool but as a server? I tried with the json-server.json file but it didn't work.

**Comment by erayerdin** [comment]
Having the same issue, but I will give some context to it.

So, when I change `db.json`, it is not a big deal. The server restarts as expected.

However, `routes.json` is a different issue:

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:3000
    at Server.setupListenHandle [as _listen2] (net.js:1294:14)
    at listenInCluster (net.js:1342:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1480:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:63:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1321:8)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

When I change something on it, it crashes and exits immediately.
