### ISSUE TITLE
Unsupported source

### ISSUE THREAD

**Issue by abhi-shk** [typicode/json-server#653]
I am using below json and getting  

`throw new Error('Unsupported source ${source}')`

Please  let me know If I am missing out anything.

`{
	"levels": [
		{
			"id": "l1",
			"name": "Round Things"
		},
		{
			"id": "l2",
			"name": "Vinegar"
		}
	],
	"products": [
		{
			"id": "p1",
			"levelId": "l1",
			"name": "Cricket Balls"
		},
		{
			"id": "p2",
			"levelId": "l1",
			"name": "Apples"
		},
		{
			"id": "p3",
			"levelId": "l1",
			"name": "Spherical Cheese"
		},
		{
			"id": "p4",
			"levelId": "l2",
			"name": "Dog Melting Vinegar"
		},
		{
			"id": "p5",
			"levelId": "l2",
			"name": "Artisinal Hand Knitted Bulgarian Yak Vinegar"
		}
	],
	"manufacturerPerformance": [
		{
			"week": 1,
			"revenueLastYear": 25,
			"revenueThisYear": 68,
			"changeInRevenue": 43,
			"unitsLastYear": 26,
			"unitsThisYear": 53,
			"changeInUnits": 27
		},
		{
			"week": 2,
			"revenueLastYear": 83,
			"revenueThisYear": 64,
			"changeInRevenue": -19,
			"unitsLastYear": 29,
			"unitsThisYear": 33,
			"changeInUnits": 4
		},
		{
			"week": 3,
			"revenueLastYear": 57,
			"revenueThisYear": 82,
			"changeInRevenue": 25,
			"unitsLastYear": 26,
			"unitsThisYear": 116,
			"changeInUnits": 90
		},
		{
			"week": 4,
			"revenueLastYear": 99,
			"revenueThisYear": 29,
			"changeInRevenue": -70,
			"unitsLastYear": 77,
			"unitsThisYear": 101,
			"changeInUnits": 24
		},
		{
			"week": 5,
			"revenueLastYear": 17,
			"revenueThisYear": 94,
			"changeInRevenue": 77,
			"unitsLastYear": 146,
			"unitsThisYear": 51,
			"changeInUnits": -95
		},
		{
			"week": 6,
			"revenueLastYear": 92,
			"revenueThisYear": 96,
			"changeInRevenue": 4,
			"unitsLastYear": 88,
			"unitsThisYear": 97,
			"changeInUnits": 9
		},
		{
			"week": 7,
			"revenueLastYear": 36,
			"revenueThisYear": 98,
			"changeInRevenue": 62,
			"unitsLastYear": 108,
			"unitsThisYear": 86,
			"changeInUnits": -22
		},
		{
			"week": 8,
			"revenueLastYear": 69,
			"revenueThisYear": 78,
			"changeInRevenue": 9,
			"unitsLastYear": 27,
			"unitsThisYear": 146,
			"changeInUnits": 119
		},
		{
			"week": 9,
			"revenueLastYear": 59,
			"revenueThisYear": 12,
			"changeInRevenue": -47,
			"unitsLastYear": 107,
			"unitsThisYear": 141,
			"changeInUnits": 34
		},
		{
			"week": 10,
			"revenueLastYear": 91,
			"revenueThisYear": 47,
			"changeInRevenue": -44,
			"unitsLastYear": 78,
			"unitsThisYear": 133,
			"changeInUnits": 55
		},
		{
			"week": 11,
			"revenueLastYear": 95,
			"revenueThisYear": 18,
			"changeInRevenue": -77,
			"unitsLastYear": 46,
			"unitsThisYear": 96,
			"changeInUnits": 50
		},
		{
			"week": 12,
			"revenueLastYear": 55,
			"revenueThisYear": 63,
			"changeInRevenue": 8,
			"unitsLastYear": 85,
			"unitsThisYear": 30,
			"changeInUnits": -55
		},
		{
			"week": 13,
			"revenueLastYear": 38,
			"revenueThisYear": 66,
			"changeInRevenue": 28,
			"unitsLastYear": 31,
			"unitsThisYear": 21,
			"changeInUnits": -10
		},
		{
			"week": 14,
			"revenueLastYear": 49,
			"revenueThisYear": 95,
			"changeInRevenue": 46,
			"unitsLastYear": 23,
			"unitsThisYear": 96,
			"changeInUnits": 73
		},
		{
			"week": 15,
			"revenueLastYear": 69,
			"revenueThisYear": 55,
			"changeInRevenue": -14,
			"unitsLastYear": 141,
			"unitsThisYear": 31,
			"changeInUnits": -110
		},
		{
			"week": 16,
			"revenueLastYear": 89,
			"revenueThisYear": 50,
			"changeInRevenue": -39,
			"unitsLastYear": 75,
			"unitsThisYear": 137,
			"changeInUnits": 62
		},
		{
			"week": 17,
			"revenueLastYear": 82,
			"revenueThisYear": 77,
			"changeInRevenue": -5,
			"unitsLastYear": 83,
			"unitsThisYear": 124,
			"changeInUnits": 41
		},
		{
			"week": 18,
			"revenueLastYear": 84,
			"revenueThisYear": 85,
			"changeInRevenue": 1,
			"unitsLastYear": 46,
			"unitsThisYear": 120,
			"changeInUnits": 74
		},
		{
			"week": 19,
			"revenueLastYear": 22,
			"revenueThisYear": 60,
			"changeInRevenue": 38,
			"unitsLastYear": 135,
			"unitsThisYear": 50,
			"changeInUnits": -85
		},
		{
			"week": 20,
			"revenueLastYear": 30,
			"revenueThisYear": 50,
			"changeInRevenue": 20,
			"unitsLastYear": 43,
			"unitsThisYear": 70,
			"changeInUnits": 27
		},
		{
			"week": 21,
			"revenueLastYear": 35,
			"revenueThisYear": 78,
			"changeInRevenue": 43,
			"unitsLastYear": 78,
			"unitsThisYear": 52,
			"changeInUnits": -26
		},
		{
			"week": 22,
			"revenueLastYear": 46,
			"revenueThisYear": 43,
			"changeInRevenue": -3,
			"unitsLastYear": 78,
			"unitsThisYear": 86,
			"changeInUnits": 8
		},
		{
			"week": 23,
			"revenueLastYear": 27,
			"revenueThisYear": 77,
			"changeInRevenue": 50,
			"unitsLastYear": 118,
			"unitsThisYear": 130,
			"changeInUnits": 12
		},
		{
			"week": 24,
			"revenueLastYear": 73,
			"revenueThisYear": 49,
			"changeInRevenue": -24,
			"unitsLastYear": 57,
			"unitsThisYear": 39,
			"changeInUnits": -18
		},
		{
			"week": 25,
			"revenueLastYear": 96,
			"revenueThisYear": 33,
			"changeInRevenue": -63,
			"unitsLastYear": 85,
			"unitsThisYear": 104,
			"changeInUnits": 19
		},
		{
			"week": 26,
			"revenueLastYear": 45,
			"revenueThisYear": 98,
			"changeInRevenue": 53,
			"unitsLastYear": 72,
			"unitsThisYear": 111,
			"changeInUnits": 39
		},
		{
			"week": 27,
			"revenueLastYear": 11,
			"revenueThisYear": 46,
			"changeInRevenue": 35,
			"unitsLastYear": 127,
			"unitsThisYear": 28,
			"changeInUnits": -99
		},
		{
			"week": 28,
			"revenueLastYear": 41,
			"revenueThisYear": 49,
			"changeInRevenue": 8,
			"unitsLastYear": 131,
			"unitsThisYear": 114,
			"changeInUnits": -17
		},
		{
			"week": 29,
			"revenueLastYear": 85,
			"revenueThisYear": 96,
			"changeInRevenue": 11,
			"unitsLastYear": 80,
			"unitsThisYear": 123,
			"changeInUnits": 43
		},
		{
			"week": 30,
			"revenueLastYear": 23,
			"revenueThisYear": 56,
			"changeInRevenue": 33,
			"unitsLastYear": 111,
			"unitsThisYear": 87,
			"changeInUnits": -24
		},
		{
			"week": 31,
			"revenueLastYear": 41,
			"revenueThisYear": 83,
			"changeInRevenue": 42,
			"unitsLastYear": 149,
			"unitsThisYear": 56,
			"changeInUnits": -93
		},
		{
			"week": 32,
			"revenueLastYear": 62,
			"revenueThisYear": 97,
			"changeInRevenue": 35,
			"unitsLastYear": 121,
			"unitsThisYear": 115,
			"changeInUnits": -6
		},
		{
			"week": 33,
			"revenueLastYear": 99,
			"revenueThisYear": 47,
			"changeInRevenue": -52,
			"unitsLastYear": 110,
			"unitsThisYear": 38,
			"changeInUnits": -72
		},
		{
			"week": 34,
			"revenueLastYear": 24,
			"revenueThisYear": 51,
			"changeInRevenue": 27,
			"unitsLastYear": 55,
			"unitsThisYear": 122,
			"changeInUnits": 67
		},
		{
			"week": 35,
			"revenueLastYear": 95,
			"revenueThisYear": 92,
			"changeInRevenue": -3,
			"unitsLastYear": 51,
			"unitsThisYear": 75,
			"changeInUnits": 24
		},
		{
			"week": 36,
			"revenueLastYear": 42,
			"revenueThisYear": 66,
			"changeInRevenue": 24,
			"unitsLastYear": 35,
			"unitsThisYear": 137,
			"changeInUnits": 102
		},
		{
			"week": 37,
			"revenueLastYear": 47,
			"revenueThisYear": 54,
			"changeInRevenue": 7,
			"unitsLastYear": 30,
			"unitsThisYear": 23,
			"changeInUnits": -7
		},
		{
			"week": 38,
			"revenueLastYear": 53,
			"revenueThisYear": 42,
			"changeInRevenue": -11,
			"unitsLastYear": 131,
			"unitsThisYear": 64,
			"changeInUnits": -67
		},
		{
			"week": 39,
			"revenueLastYear": 60,
			"revenueThisYear": 59,
			"changeInRevenue": -1,
			"unitsLastYear": 143,
			"unitsThisYear": 29,
			"changeInUnits": -114
		},
		{
			"week": 40,
			"revenueLastYear": 53,
			"revenueThisYear": 18,
			"changeInRevenue": -35,
			"unitsLastYear": 46,
			"unitsThisYear": 63,
			"changeInUnits": 17
		},
		{
			"week": 41,
			"revenueLastYear": 82,
			"revenueThisYear": 43,
			"changeInRevenue": -39,
			"unitsLastYear": 121,
			"unitsThisYear": 72,
			"changeInUnits": -49
		},
		{
			"week": 42,
			"revenueLastYear": 99,
			"revenueThisYear": 10,
			"changeInRevenue": -89,
			"unitsLastYear": 124,
			"unitsThisYear": 39,
			"changeInUnits": -85
		},
		{
			"week": 43,
			"revenueLastYear": 31,
			"revenueThisYear": 53,
			"changeInRevenue": 22,
			"unitsLastYear": 60,
			"unitsThisYear": 144,
			"changeInUnits": 84
		},
		{
			"week": 44,
			"revenueLastYear": 30,
			"revenueThisYear": 82,
			"changeInRevenue": 52,
			"unitsLastYear": 58,
			"unitsThisYear": 41,
			"changeInUnits": -17
		},
		{
			"week": 45,
			"revenueLastYear": 73,
			"revenueThisYear": 40,
			"changeInRevenue": -33,
			"unitsLastYear": 24,
			"unitsThisYear": 64,
			"changeInUnits": 40
		},
		{
			"week": 46,
			"revenueLastYear": 64,
			"revenueThisYear": 30,
			"changeInRevenue": -34,
			"unitsLastYear": 64,
			"unitsThisYear": 68,
			"changeInUnits": 4
		},
		{
			"week": 47,
			"revenueLastYear": 61,
			"revenueThisYear": 35,
			"changeInRevenue": -26,
			"unitsLastYear": 122,
			"unitsThisYear": 75,
			"changeInUnits": -47
		},
		{
			"week": 48,
			"revenueLastYear": 41,
			"revenueThisYear": 77,
			"changeInRevenue": 36,
			"unitsLastYear": 119,
			"unitsThisYear": 34,
			"changeInUnits": -85
		},
		{
			"week": 49,
			"revenueLastYear": 81,
			"revenueThisYear": 18,
			"changeInRevenue": -63,
			"unitsLastYear": 122,
			"unitsThisYear": 43,
			"changeInUnits": -79
		},
		{
			"week": 50,
			"revenueLastYear": 77,
			"revenueThisYear": 36,
			"changeInRevenue": -41,
			"unitsLastYear": 36,
			"unitsThisYear": 138,
			"changeInUnits": 102
		},
		{
			"week": 51,
			"revenueLastYear": 68,
			"revenueThisYear": 40,
			"changeInRevenue": -28,
			"unitsLastYear": 130,
			"unitsThisYear": 148,
			"changeInUnits": 18
		},
		{
			"week": 52,
			"revenueLastYear": 13,
			"revenueThisYear": 23,
			"changeInRevenue": 10,
			"unitsLastYear": 115,
			"unitsThisYear": 25,
			"changeInUnits": -90
		}
	],
	"categoryData": [
		{
			"value": "c1",
			"name": "Category 1"
		},
		{
			"value": "c2",
			"name": "Category 2"
		},
		{
			"value": "c3",
			"name": "Category 3"
		},
		{
			"value": "c4",
			"name": "Category 4"
		},
		{
			"value": "c5",
			"name": "Category 5"
		}
	]
}`

**Comment by praveen612** [comment]
@abhi-shk copy pasted the above data into `db.json` file and running `json-server db.json` worked for me. 
If you can make a gist of how you are using it with json-server I can help more

**Comment by adityasood11** [comment]
Hi,

I am getting similar error.
I  validated my Json using 'https://jsonlint.com' as well. Cant figure out whats causing the error.

Unsupported source ($filename)
    at Promise (C:\Users\Aditya2.Sood\AppData\Roaming\npm\node_modules\json-server\lib\cli\utils\load.js:71:13)
    at new Promise (<anonymous>)
    at module.exports (C:\Users\Aditya2.Sood\AppData\Roaming\npm\node_modules\json-server\lib\cli\utils\load.js:36:10)
    at start (C:\Users\Aditya2.Sood\AppData\Roaming\npm\node_modules\json-server\lib\cli\run.js:110:12)
    at module.exports (C:\Users\Aditya2.Sood\AppData\Roaming\npm\node_modules\json-server\lib\cli\run.js:147:3)
    at module.exports (C:\Users\Aditya2.Sood\AppData\Roaming\npm\node_modules\json-server\lib\cli\index.js:86:3)
    at Object.<anonymous> (C:\Users\Aditya2.Sood\AppData\Roaming\npm\node_modules\json-server\lib\cli\bin.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

**Comment by adityasood11** [comment]
Hi @d205 ,
I encountered the same error because i made a silly mistake.

I was using this command
json-server --watch $filename --port  $portnumber

It was showing me unsupported source data because my source  was incorrect.

The correct command is
json-server --watch $filename.json --port $portnumber

I am sure this will solve your issue.

**Comment by biogray** [comment]
I run into the same issue, and here is what worked for me.
1. disable Local Area Connection  _(right click Disable)_
2.  restart your windows
3. Local Area Connection should be still disabled
4. run your command eg:   npx json-server -p 3500 -w db.json
5. Once its running you can enable Local Area Connection now.
