### ISSUE TITLE
Query for null

### ISSUE THREAD

**Issue by marukx** [typicode/json-server#682]
This is a questions, something that i didn't manage to find in documentation. 

However it seems like a basic functionality and I'm sure that there must be a simple solution/workaround.

I've got a requirement to get all records where date is null, tried 

http://localhost:3000/entity_name?date=null

with no luck as it does not return any records. 

Had a look at the following issue and i can see that author suggested adding new _is_null operator. 
https://github.com/typicode/json-server/issues/510

However not sure if this was added. 

Any help would be appreciated. 

MK

**Comment by Nilegfx** [comment]
use `json-server` as nodejs module not CLI (command line) and override `router.render` method with the filtration logic 

```js
const jsonServer = require('json-server');
const server = jsonServer.create();
const router = jsonServer.router('db.json');
const middlewares = jsonServer.defaults();

router.render = (req, res) => {
   let data = res.locals.data;

   // a very dirty way to check if there is a filter by date and the response is an array
   if(req.query.date_is_null && typeof data !== 'function' && data.length ) {
     res.send(data.filter(d => !d.date))
   }
}

//default json-server middlewares
server.use(middlewares);

// json-server's magic
server.use(router);

server.listen(3000, () => {
  console.log('http://localhost:3000');
});
```

**Comment by marukx** [comment]
thanks will do that

**Comment by Kiro24** [comment]
> as a temporary solution until this feature merged, you could use `json-server` as nodejs module not CLI (command line) and override `router.render` method with the filtration logic
> ### server.js
> 
> ```js
> const jsonServer = require('json-server');
> const server = jsonServer.create();
> const router = jsonServer.router('db.json');
> const middlewares = jsonServer.defaults();
> 
> router.render = (req, res) => {
>    let data = res.locals.data;
> 
>    // a very dirty way to check if there is a filter by date and the response is an array
>    if(req.query.date_is_null && typeof data !== 'function' && data.length ) {
>      res.send(data.filter(d => !d.date))
>    }
> }
> 
> //default json-server middlewares
> server.use(middlewares);
> 
> // json-server's magic
> server.use(router);
> 
> server.listen(3000, () => {
>   console.log('http://localhost:3000');
> });
> ```
> 
> run it:
> 
> ```shell
> node server.js
> ```
> 
> Please test the code as I wrote it without running it, so it could have some syntax errors

could you please elaborate more?

So I tried creating a new file called server.js in the same directory where the db is located and copied the above code and ran the cammand node server.js in the same dir
I got this error

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'json-server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ti5a/dev/vlum/fake/server.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
