### ISSUE TITLE
Embedding with a Many to Many

### ISSUE THREAD

**Issue by bertmckay79** [typicode/json-server#714]
Hi,

I've seen several of the posts regarding one to many and many to many implementations but I can't quite get them to work for me.

Here's an example of my json
`[
processes: [{
id: 1,
processname: 'Process 1'
},
{
id: 2,
processname: 'Process 2'
}],
categories: [
{
id: 1,
categoryname: 'Category 1'
},
{
id: 2,
categoryname: 'Category 2'
},
{
id: 3,
categoryname: 'Category 3'
}],
processcategories: [
{
processId: 1,
categoryId: 1
},
{
processId: 1,
categoryId: 3
},
{
processId: 2,
categoryId: 2
},
{
processId: 2,
categoryId: 3
},
]
]`

What I'd like to be able to do is call /Processes?_embed=Category but it's not returning anything.
I've tried this but ProcessCategories?_expand=Process it's throwing the following exception:

TypeError: Cannot read property 'toString' of undefined at D:\home\site\wwwroot\node_modules\lodash-id\src\index.js:37:50 at baseFindIndex (D:\home\site\wwwroot\node_modules\lodash\lodash.js:823:11) at findIndex (D:\home\site\wwwroot\node_modules\lodash\lodash.js:7275:14) at Function.find (D:\home\site\wwwroot\node_modules\lodash\lodash.js:5098:21) at Function.getById (D:\home\site\wwwroot\node_modules\lodash-id\src\index.js:35:17) at D:\home\site\wwwroot\node_modules\lodash\lodash.js:4379:28 at arrayReduce (D:\home\site\wwwroot\node_modules\lodash\lodash.js:704:21) at baseWrapperValue (D:\home\site\wwwroot\node_modules\lodash\lodash.js:4378:14) at LodashWrapper.wrapperValue (D:\home\site\wwwroot\node_modules\lodash\lodash.js:9067:14) at D:\home\site\wwwroot\node_modules\json-server\lib\server\router\plural.js:32:74

Am I missing something?

Cheers
Bert

**Comment by bertmckay79** [comment]
Ok, I figure out what was wrong with this: ProcessCategories?_expand=Process 
I'd a type in the generation process resulting in processid.

**Comment by ayazzali** [comment]
sorry but i cant do this too 
![image](https://user-images.githubusercontent.com/19633435/39087278-0a51c0ec-459f-11e8-92f7-4589677273aa.png)
