### ISSUE TITLE
why throw a error : The database is a JavaScript file but the export is not a function？

### ISSUE THREAD

**Issue by LuckyDing** [typicode/json-server#716]
db.js
`module.exports = () => {
  const data = { users: [] }
  // Create 1000 users
  for (let i = 0; i < 1000; i++) {
    data.users.push({ id: i, name: `user${i}` })
  }
  return data
}
`
index.js
`const path = require('path')
const jsonServer = require('json-server')
const ip = require('ip').address()
const db = require('./db')

const server = jsonServer.create()
const router = jsonServer.router(db())
const middlewares = jsonServer.defaults()

server.use(middlewares)
server.use(router)
server.listen({
    host: "localhost",
    port: 9090
}, function() {
    console.log(`JSON Server is running in http://${ip}:9090`)
})
`

**Comment by lautaros86** [comment]
I have the same error.

//server.js
var jsonServer = require('json-server')
var server = jsonServer.create()
var router = jsonServer.router('db.json')
var middlewares = jsonServer.defaults()
server.use(middlewares)
server.listen(3000, () => {
  console.log('JSON Server is running')
})

//db.json
{
  "user": [
    {
      "id": 1,
      "nombre": "asdasd",
      "apellido": "Siasdasdlva",
      "mail": "asdads"
    }
  ]
}

//routes.json
{
  "/api/*": "/$1",
  "/:resource/:id/show": "/:resource/:id",
  "/api/user": "/usuario/1"
}

when i execute #>json-server server.js --routes routes.json


  \{^_^}/ hi!

  Loading server.js
C:\Users\Lautaro\AppData\Roaming\npm\node_modules\json-server\lib\cli\utils\load.js:28
      throw new Error('The database is a JavaScript file but the export is not a function.');
      ^

Error: The database is a JavaScript file but the export is not a function.
    at module.exports (C:\Users\Lautaro\AppData\Roaming\npm\node_modules\json-server\lib\cli\utils\load.js:28:13)
    at start (C:\Users\Lautaro\AppData\Roaming\npm\node_modules\json-server\lib\cli\run.js:122:5)
    at module.exports (C:\Users\Lautaro\AppData\Roaming\npm\node_modules\json-server\lib\cli\run.js:159:3)
    at module.exports (C:\Users\Lautaro\AppData\Roaming\npm\node_modules\json-server\lib\cli\index.js:81:3)
    at Object.<anonymous> (C:\Users\Lautaro\AppData\Roaming\npm\node_modules\json-server\lib\cli\bin.js:3:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)


//================================================================//

if execute 
"node server.js --routes routes.json"

Basic server works but custom routes are ignored.

some idea?

**Comment by harshal-wani** [comment]
facing the same issue. Any help?

**Comment by pravin02pal** [comment]
Same issue is facing on my end. How can resolve this issue?

**Comment by Surdok** [comment]
Same issue here.

**Comment by vollmerr** [comment]
It looks like the cli load file validation is checking the output of the server file instead of the route file for comparing if it is a function.  I found this temporary work around of re-exporting the route file so it is read in the validation, though appears to have its limitations and seems to only work for using a js route file and not json.


```
const jsonServer = require('json-server');
const generate = require('./generate');

const server = jsonServer.create();
const router = jsonServer.router(generate());
const middlewares = jsonServer.defaults();
server.use(middlewares);
server.use(router);

// This is being ignored. Automatically starts on 3000 so will have to pass --port to cli when calling
// server.listen(3001, () => {
//   console.log('Mock Server is running on 3001');
// });

module.exports = generate;
```

**Comment by lbqfsj** [comment]
same issue
