### ISSUE TITLE
SyntaxError: Unexpected token :

### ISSUE THREAD

**Issue by demetrioin** [typicode/json-server#809]
I followed https://github.com/typicode/json-server by installing globally json-server and I copied form that page db.json. When Itry run such file I get Unexpeccted token. In case it matter, I am using Windows 7.

C:\json-server\hello-world\customers.js:2
  "posts" : [
          ^

SyntaxError: Unexpected token :
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at module.exports (C:\Users\my-user\AppData\Roaming\npm\node_modules\json-server\lib\cli\utils\load.js:25:20)

Here is my version

C:\json-server\hello-world>npm version
{ npm: '5.6.0',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.11.1',
  openssl: '1.0.2o',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.1',
  v8: '6.2.414.50',
  zlib: '1.2.11' }

C:\json-server\hello-world>json-server -v
0.14.0

**Comment by JoshuaScript** [comment]
It seems you've saved your 'customers' file as a JavaScript file instead of JSON. It should be `customers.json` instead of `customers.js`
