### ISSUE TITLE
Get error when trying to delete file

### ISSUE THREAD

**Issue by bogdantarasenkozp** [typicode/json-server#815]
get error on any delete request

TypeError: Cannot read property 'toString' of null
    at /home/bogdan/projects/dms/server/node_modules/lodash-id/src/index.js:37:51
    at baseFindIndex (/home/bogdan/projects/dms/server/node_modules/lodash/lodash.js:794:11)
    at findIndex (/home/bogdan/projects/dms/server/node_modules/lodash/lodash.js:7250:14)
    at Function.find (/home/bogdan/projects/dms/server/node_modules/lodash/lodash.js:5071:21)
    at Function.getById (/home/bogdan/projects/dms/server/node_modules/lodash-id/src/index.js:35:17)
    at /home/bogdan/projects/dms/server/node_modules/json-server/lib/server/mixins.js:26:25
    at /home/bogdan/projects/dms/server/node_modules/lodash/lodash.js:4917:15
    at baseForOwn (/home/bogdan/projects/dms/server/node_modules/lodash/lodash.js:3002:24)
    at /home/bogdan/projects/dms/server/node_modules/lodash/lodash.js:4886:18
    at Function.forEach (/home/bogdan/projects/dms/server/node_modules/lodash/lodash.js:9334:14)

**Comment by JoshuaScript** [comment]
Can you share the source code of your index.js?

**Comment by Rock-son** [comment]
Well, I had the exact same error at the exact same line numbers and debugged the hell out of it and came to a conclusion that no foreign key with **id** in it's name should be **null**. The check throws an error when it finds one, so I set it to -1 and then it workes ok. 

This problem basically  annoys anyone having a **zero or many** or **zero or one** relations in their tables, since it doesn't return any results on deletion. At "node_modules/json-server/lib/server/mixins.js:22:9" a check for **null** in value besides the foreign key, would be enough.

**Comment by maxhille** [comment]
Just in case someone else stumbles over this. I solved this issue for me by adding some debug prints to find the offending values in our mock-db.

`node_modules/json-server/lib/server/mixins.js:`

```js
          const refName = pluralize.plural(key.replace(new RegExp(`${opts.foreignKeySuffix}$`), '')); // Test if table exists

          if (db[refName]) {
            console.log("refName " + refName);
            console.log("value " + value);
            console.log("key " + key);
            // Test if references is defined in table
            const ref = _.getById(db[refName], value);

            if (_.isUndefined(ref)) {
              removable.push({
                name: collName,
                id: doc.id
              });
            }
          }
```
