### ISSUE TITLE
Routes JSON Throws Syntax Error on server start

### ISSUE THREAD

**Issue by thetypebeast** [typicode/json-server#822]
I input the following command and get an immediate response back:

~~~
$ json-server --watch wwwroot/content/data/favorites.json --routes wwwroot/content/data/routes.json

  \{^_^}/ hi!

  Loading wwwroot/content/data/favorites.json
  Loading wwwroot/content/data/routes.json
undefined:1
﻿{
^

SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at load (C:\Users\byers.jennifer\AppData\Roaming\npm\node_modules\json-server\lib\cli\run.js:132:23)
    at module.exports (C:\Users\byers.jennifer\AppData\Roaming\npm\node_modules\json-server\lib\cli\utils\load.js:37:5)
    at start (C:\Users\byers.jennifer\AppData\Roaming\npm\node_modules\json-server\lib\cli\run.js:125:5)
    at module.exports (C:\Users\byers.jennifer\AppData\Roaming\npm\node_modules\json-server\lib\cli\run.js:162:3)
    at module.exports (C:\Users\byers.jennifer\AppData\Roaming\npm\node_modules\json-server\lib\cli\index.js:81:3)
    at Object.<anonymous> (C:\Users\byers.jennifer\AppData\Roaming\npm\node_modules\json-server\lib\cli\bin.js:3:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
~~~

This is _favorites.json_:
~~~
{
  "favorites": [
    {
      "id": "1",
      "favorite_id": "772",
      "target": "path/to/screen1",
      "breadcrumb": "Path > To > Screen 1",
      "sort_order": "1"
    },
    {
      "id": "2",
      "favorite_id": "775",
      "target": "path/to/screen2",
      "breadcrumb": "Path > To > Screen 2",
      "sort_order": "2"
    }
  ]
}
~~~

This is _routes.json_:
~~~
{
  "/favorites/:id" : "/favorites?favorites_id=:id" 
}
~~~

Everything works normally when NOT using the `--routes` flag, but when I use the `--routes` flag,  I get this error. I created _routes.json_ using the instructions here: [Add Custom Routes](https://github.com/typicode/json-server#add-custom-routes).

What is going on?

**Comment by kotoo** [comment]
hi! i can try to help you. all works fine for me with your json-files, which i created by scratch in linux. but i trying to add BOM symbol to routes.json for experiment, and i have the same error after this. may be the problem lies in this?
