### ISSUE TITLE
Unable to start in Starbucks :-)

### ISSUE THREAD

**Issue by mikeerickson** [typicode/json-server#827]
I know this is a weird report, but I am having an issue starting `json-server` when I am in stucks on their public wifi (I an start at work and home no problem on their wifi).  Does anybody have a trick for making this work?

Starting server as

```
json-server --watch --port=5000 data.json

// using default 3000 port
json-server --watch data.json

```bash

Error reported

events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
Emitted 'error' event at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1499:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:17)
```

**Comment by mikeerickson** [comment]
Duh, I had a brain fart (too much muscle memory).

```
Accessing as 127.0.0.1:5000 
```

works just fine :-)

**Comment by tuzmusic** [comment]
Mike can you explain what you realized? Did you change the command at all? 

I'm getting the error no matter what port I try: 
```bash
// ♥ json-server --watch tests/mocks/StationsMock.json

  \{^_^}/ hi!

  Loading tests/mocks/StationsMock.json
  Done

  Resources
  http://localhost:3000/stations

  Home
  http://localhost:3000

  Type s + enter at any time to create a snapshot of the database
  Watching...

Some error occurred { Error: getaddrinfo ENOTFOUND localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'localhost' }
```

**Comment by mikeerickson** [comment]
@tuzmusic I used `127.0.0.1` instead of `localhost`

**Comment by leonalicious** [comment]
please check if `Nginx` is running, turn it off and try again

**Comment by soakit** [comment]
```shell
ping localhost
```
if no response, add the following in your host file
```
127.0.0.1 localhost
```

or just change your `json-server` host

```shell
json-server your_json.json --watch --host 127.0.0.1 
```
