### ISSUE TITLE
Can't get it to start - Windows 7

### ISSUE THREAD

**Issue by Shaunakde** [typicode/json-server#83]
I am running npm 2.7.4 on Windows 7 with node 0.12.2
When I try to get the package running from the github main branch I get the following error:

```
D:\Shaunak\Scratch\fakejsonserv>npm start

> json-server@0.7.5 start D:\Shaunak\Scratch\fakejsonserv
> node server.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'D:\Shaunak\Scratch\fakejsonserv\server.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! json-server@0.7.5 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the json-server@0.7.5 start script 'node server.js'.
npm ERR! This is most likely a problem with the json-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls json-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Shaunak\Scratch\fakejsonserv\npm-debug.log

D:\Shaunak\Scratch\fakejsonserv>
```

I am tinkering, will update this thread.

SD

**Comment by Shaunakde** [comment]
Okay, I clearly was doing something wrong. Let me clarify what I was trying to achieve and what was my mistake so that those searching in the future can benefit. 

I was trying to get it to work from the bin provided / source code. Clearly the `npm install` / `npm start` combination did not work as listed above. So the provided bin file can be run from the `/bin` directory as follows:
`node ./bin/index.js data.json`

**Comment by typicode** [comment]
It's a bug in the `json-server` start script too. Thanks for raising the issue and the explanation :+1:
