### ISSUE TITLE
Setting host to ip address gives EADDRNOTAVAIL

### ISSUE THREAD

**Issue by stuart68** [typicode/json-server#838]
Hi,

I have just started running json-server.

Yesterday I had no issues with running this on a VM. The VM is using Ubuntu 18.04. With nide version v8.10.0 and json-server version 0.14.0.

I started the server with:

json-server --host 172.x.x.x db.json

Today this does not work. The server will only run if I use the default of localhost. 

What have I done wrong? I am new to node and json-server.

Thanks for any help

**Comment by stuart68** [comment]
`events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 172.16.1.58:3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1350:19)
    at listenInCluster (net.js:1408:12)
    at doListen (net.js:1517:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
`

**Comment by ikismail** [comment]
I got the same issue,
This occurs when the IP is not exists....
I solved it by providing the valid IP Address. 
@stuart68  Please double check your HOST IP

**Comment by jDelta** [comment]
Hi,
Use this:
json-server --host 0.0.0.0 db.json
