### ISSUE TITLE
Remove errorhandler dependency because it is causing issues when bundling

### ISSUE THREAD

**Issue by casertap** [typicode/json-server#855]
I would like to bundle my json-server using webpack.
I have a very simple webpack config, my express server is working well with the command:
```
node fake-backend/babel.server.js
```
As soon as I bundle and run the server again I get those errors:
```
node dist/server.js
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/public/style.css'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/................/dist/server.js:40247:21
```

It is the package:
```
─┬ json-server@0.14.0
  └── errorhandler@1.5.0
```
that is loading some static files like that:
```
var DOUBLE_SPACE_REGEXP = /\x20{2}/g
var NEW_LINE_REGEXP = /\n/g
var STYLESHEET = fs.readFileSync(path.join(__dirname, '/public/style.css'), 'utf8')
var TEMPLATE = fs.readFileSync(path.join(__dirname, '/public/error.html'), 'utf8')
var inspect = util.inspect
var toString = Object.prototype.toString
```
Because it is not using require webpack is not able to find them.

**Comment by casertap** [comment]
An easy fix for this one would be to push the `const errorhandler = require('errorhandler')`
inside the conditional where is it used:
```
if (process.env.NODE_ENV === 'development') {
 // only use in development
 const errorhandler = require('errorhandler')
 arr.push(errorhandler())
 }
```

**Comment by casertap** [comment]
here is a PR: https://github.com/typicode/json-server/pull/856

**Comment by vreddi** [comment]
I hitting this issue while bundling this with web-pack. Any way this could be fixed on the client without making change to json-server?

**Comment by jpiersol** [comment]
I've been able to work around this by declaring errorhandler as a [string external](https://v4.webpack.js.org/configuration/externals/#string) in the webpack config:

```ts
const webpackConfig = {
  externals: [
    { 'errorhandler': '{}' },
    ...
  ],
  ...
}
```

From reading the docs, I _think_ this is replacing refs to errorhandler with an empty object, and I assume the uses of errorhandler are simply failing silently.

In any case, I can now run the bundle without the errorhandler error, using `node dist/index.js`.

**Comment by alexcroox** [comment]
Same problem in 2022, are the above workarounds still applicable? I see the PR to move it to a dev env include haven't been merged yet...
