### ISSUE TITLE
Whan i try server `json-server --watch db.json --port 3003` i get error 

### ISSUE THREAD

**Issue by mackrais** [typicode/json-server#871]
> I have free space on my disk 141.9 GB

  \{^_^}/ hi!

  Loading db.json
  Done

  Resources
  http://localhost:3003/users
  http://localhost:3003/bill
  http://localhost:3003/categories
  http://localhost:3003/events

  Home
  http://localhost:3003

  Type s + enter at any time to create a snapshot of the database
  Watching...

internal/fs/watchers.js:170
    throw error;
    ^

Error: ENOSPC: no space left on device, watch '.'
    at FSWatcher.start (internal/fs/watchers.js:164:26)
    at Object.watch (fs.js:1232:11)
    at start (/usr/local/lib/node_modules/json-server/lib/cli/run.js:198:10)
    at load (/usr/local/lib/node_modules/json-server/lib/cli/run.js:159:13)
    at module.exports (/usr/local/lib/node_modules/json-server/lib/cli/utils/load.js:37:5)
    at start (/usr/local/lib/node_modules/json-server/lib/cli/run.js:127:5)
    at module.exports (/usr/local/lib/node_modules/json-server/lib/cli/run.js:164:3)
    at module.exports (/usr/local/lib/node_modules/json-server/lib/cli/index.js:81:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/json-server/lib/cli/bin.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)

**Comment by mnemosdev** [comment]
Error: ENOSPC

Seems you have no space left, have you checked the storage? Are you using some kind of third-party application environment (cloud9 or similar)?

That would be helpful to know
