### ISSUE TITLE
bodyParser.json is not a function

### ISSUE THREAD

**Issue by bbva-franciscocalle** [typicode/json-server#881]
Hi

I'm starting a json-server for my test using jest, doing something similar to what is done in this project, but when starting the server, I get this error:

```
    TypeError: bodyParser.json is not a function

      at Object.<anonymous> (node_modules/json-server/lib/server/body-parser.js:6:14)
      at Object.<anonymous> (node_modules/json-server/lib/server/defaults.js:11:20)
      at Object.<anonymous> (node_modules/json-server/lib/server/index.js:7:13)
```

It seems to me that the problem is that the `require('body-parser')` in body-parser.js:6:14 is not resolving properly due to a conflict with itself. I've run a test modifying the filename to bp.js and changing the references to it and it seems if fixes the issue.

**Comment by miun173** [comment]
I'm facing issue with `jsonServer.bodyParser` too, that it can't handle the post request. Installing `bodyParser` and use it, instead of `jsonServer.bodyParser` solved my issue
