### ISSUE TITLE
db.getState is not a function

### ISSUE THREAD

**Issue by saury** [typicode/json-server#898]
Hi, 

I follow the README.MD to create this `Access control example`. 
Both `server.js` and `db.json` are created. 
But why I always get this error after running `node server.js`? Anyone can help?
Extra info: macOS, node@10, json-server@0.14.1

```
*/node_modules/json-server/lib/server/router/index.js:44
validateData(db.getState()); // Add lodash-id methods to db
                ^
TypeError: db.getState is not a function
at Object.module.exports [as router] (*/node_modules/json-server/lib/server/router/index.js:44:19)
```

**Comment by zhaoxianxin** [comment]
I found this problem too.

validateData(db.getState()); // Add lodash-id methods to db
                  ^
TypeError: db.getState is not a function

**Comment by saury** [comment]
> I found this problem too.
> 
> validateData(db.getState()); // Add lodash-id methods to db
> ^
> TypeError: db.getState is not a function

You can downgrade to 0.14.0 for preventing this error.

**Comment by alxmiron** [comment]
Also got the `db.getState is not a function` error in v0.14.1

**Comment by typicode** [comment]
Thanks for the report :) should be good in v0.14.2

**Comment by xeoshow** [comment]
@typicode I still got same error, please see below detail info:
~~~
[nodejs@xiu-v3-test ~]$ lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.8 (Final)
Release:	6.8
Codename:	Final
[nodejs@xiu-v3-test ~]$ node -v
v10.13.0
[nodejs@xiu-v3-test ~]$ json-server -v
0.14.2
[nodejs@xiu-v3-test ~]$ ls
db.json   node_modules             node-v10.13.0-linux-x64.tar.xz  server.js
https.js  node-v10.13.0-linux-x64  package-lock.json               ssl
[nodejs@xiu-v3-test ~]$ node server.js 
/home/nodejs/node_modules/json-server/lib/server/router/index.js:44
  validateData(db.getState()); // Add lodash-id methods to db
                  ^

TypeError: db.getState is not a function
    at Object.module.exports [as router] (/home/nodejs/node_modules/json-server/lib/server/router/index.js:44:19)
    at Object.<anonymous> (/home/nodejs/server.js:4:27)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
[nodejs@xiu-v3-test ~]$ 
~~~

Below is the file server.js:
~~~
// server.js
const jsonServer = require('json-server')
const server = jsonServer.create()
const router = jsonServer.router('db.json')
const middlewares = jsonServer.defaults()

server.use(middlewares)
server.use(router)
server.listen(3389, () => {
  console.log('JSON Server is running')
})
~~~
