### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by djvang** [typicode/json-server#911]
Check please this URL - https://jsonplaceholder.typicode.com/posts/1?_embed=comments&_expand=user

I see this error:

`
TypeError: Cannot read property 'toString' of undefined at /app/node_modules/lodash-id/src/index.js:37:51 at baseFindIndex (/app/node_modules/lodash/lodash.js:802:11) at findIndex (/app/node_modules/lodash/lodash.js:7260:14) at Function.find (/app/node_modules/lodash/lodash.js:5065:21) at Function.getById (/app/node_modules/lodash-id/src/index.js:35:17) at /app/node_modules/lodash/lodash.js:4374:28 at arrayReduce (/app/node_modules/lodash/lodash.js:683:21) at baseWrapperValue (/app/node_modules/lodash/lodash.js:4373:14) at LodashWrapper.wrapperValue (/app/node_modules/lodash/lodash.js:9052:14) at e.concat.forEach.innerResource (/app/node_modules/json-server/lib/server/router/plural.js:44:74)
`

**Comment by ikarus93** [comment]
I am facing the same issue trying to access a nested resource. Any new input?

**Comment by spaenleh** [comment]
Same here

**Comment by joegregory-cbe** [comment]
Still an issue. But I normally use jsonserver as a module with some modifications. One of those is to use uuids with the provided mixin:
```js
this.db._.mixin({
      createId() {
        return uuidv4();
      },
});
```

Then expand works like expected.
