### ISSUE TITLE
Unknown error listening on port 3000

### ISSUE THREAD

**Issue by eappell** [typicode/json-server#924]
I've been using json-server for a couple months now with no issues until this morning.  I went to run it and I get this error:

`
Some error occurred { Error: listen EACCES 127.0.0.1:3000
    at Server.setupListenHandle [as _listen2] (net.js:1343:19)
    at listenInCluster (net.js:1401:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1510:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:72:10)
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 3000 }
`

I checked and no other processes are using port 3000.  Looking at the error, I have no idea where to even start debugging this.  I checked the json file I use to make sure I don't have duplicate root nodes, or some other strange content in there that could cause an issue, and it's clean.  I'm not sure what else to do.  Any help is appreciated!

**Comment by eappell** [comment]
Turned out it was something about my session.  After I rebooted my machine the same db.json file loaded just fine.
