### ISSUE TITLE
AppVeyor fails running tests for cli/index.js due to missing transpiling of make-dir module

### ISSUE THREAD

**Issue by tpiekarski** [typicode/json-server#979]
After opening one PR (#978) here I encountered, that AppVeyor fails running the test for **cli/index.js** with following message. 

> FAIL __tests__/cli/index.js
  ● Test suite failed to run
    Jest encountered an unexpected token
    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html
    Details:
    C:\projects\json-server\node_modules\temp-write\node_modules\make-dir\index.js:42
    		...defaults,
    		^^^
    SyntaxError: Unexpected token ...
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
      at Object.<anonymous> (node_modules/temp-write/index.js:6:17)

It did not think it would have something to do with my PR. So I created a project at AppVeyor with my fork of this repository to check if master is still building there. But the same error like with the mentioned PR occurred.

Logs from the build of master from my fork at AppVeyor:
https://ci.appveyor.com/project/tpiekarski/json-server/builds/25468732

**Comment by tpiekarski** [comment]
After some tests, I discovered that AppVeyor was still using version 7 and not 8 of Node. With bumping this version the tests from cli/index.js are running and are green again. So no transformIgnorePatterns for jest :)
